### ISSUE TITLE
Test Result Trend graph missing

### ISSUE THREAD

**Issue by claycephas** [zeroturnaround/build-flow-test-aggregator#12]
When a free-style project publishes test results, it makes a Test Result Trend graph appear on the project.
![image](https://cloud.githubusercontent.com/assets/469582/8166133/2567310e-1353-11e5-9d7f-a27d0a8240fe.png)

However, after adding the "Aggregate build flow test results" as a post-build action, the Test Result Trend Graph does not appear for the build flow job. I do have the "Flow run needs a workspace" checkbox checked on the build flow job.

**Comment by poolik** [comment]
Hi @claycephas!

This is currently intentionally so, because I first created this plugin to easily see test results in flow job that dynamically changes the tests that it runs. Meaning the test results trend report would be all over the place because at one point I might have 100 test running and on next build just 5 for example.

Though this has been requested before so I've considered making it configurable, whether to include this or not. In 1 weeks time my vacation starts to I might implement this then and release version 1.2 of the plugin.

**Comment by bridadan** [comment]
I too would like this! I'd be happy to help test and/or help implement.

**Comment by bluedevils23** [comment]
Yes, this feature is very useful for us. configurable is a good option.
